apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-artemis-users
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: Opaque
stringData:
  users.properties: |
    {{- .Files.Get "users.properties" | nindent 4 }}
