{{- $secretName := printf "%s-mongodb-hono-secret" (include "dt4mob.fullname" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "dt4mob.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $secretName) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $password := (get $secretData "password" | b64dec) | default (randAlphaNum 16) }}
  password: {{ $password | b64enc | quote }}
