use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum Action {
    #[serde(rename = "modified")]
    Modified,
    #[serde(rename = "created")]
    Created,
    #[serde(rename = "deleted")]
    Deleted,
    #[serde(rename = "merged")]
    Merged,
}

impl TryFrom<&str> for Action {
    type Error = String;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        match value {
            "modified" => Ok(Action::Modified),
            "created" => Ok(Action::Created),
            "deleted" => Ok(Action::Deleted),
            "merged" => Ok(Action::Merged),
            _ => Err(format!("Unknown action: {}", value)),
        }
    }
}

impl std::fmt::Display for Action {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Action::Modified => write!(f, "modified"),
            Action::Created => write!(f, "created"),
            Action::Deleted => write!(f, "deleted"),
            Action::Merged => write!(f, "merged"),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DittoEvent {
    pub time: DateTime<Utc>,
    pub thing_id: String,
    pub action: Action,
    pub revision: Option<i32>,
    pub path: String,
    pub value: Option<Value>,
}

pub const DDL_SQL: &str = r#"
CREATE TABLE IF NOT EXISTS dittoevent (
    time TIMESTAMPTZ NOT NULL,
    index INTEGER GENERATED BY DEFAULT AS IDENTITY,
    thing_id VARCHAR NOT NULL,
    action VARCHAR NOT NULL,
    revision INTEGER,
    path VARCHAR NOT NULL,
    value JSONB,
    PRIMARY KEY (time, index)
);

SELECT create_hypertable('dittoevent', 'time', chunk_time_interval => INTERVAL '1 day', if_not_exists => TRUE);

ALTER TABLE dittoevent SET (
    timescaledb.compress,
    timescaledb.compress_segmentby = 'thing_id',
    timescaledb.compress_orderby = 'time DESC'
);

SELECT add_compression_policy('dittoevent', INTERVAL '7 days', if_not_exists => TRUE);

CREATE INDEX IF NOT EXISTS idx_dittoevent_thing_id ON dittoevent (thing_id);
"#;
